matches: 
  - regex: "4"
    replace: "owo"
  - regex: "5"
    replace: "owoh"
  - regex: "6"
    replace: "owob"
  - regex: "7"
    replace: "owobuy 1"
  - regex: "9"
    replace: "owopray {{clipb}}"
    vars:
      - name: "clipb"
        type: "clipboard"
